services:
  ai:
    container_name: pytorch_dev
    hostname: pytorch-env
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true
    # runtime: nvidia  # remove if not using GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
